version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  es_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.32.25.118,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/prox-pool/Coolnow/docker/elasticsearch/data"
